# Generated by Django 5.2 on 2025-04-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('view_client_custom', 'Can view client')]},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('view_mailing_custom', 'Can view mailing')]},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('view_message_custom', 'Can view message')]},
        ),
    ]
